### PR TITLE
Rebuild for grpc_cpp147

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I am trying to build the latest release of `google-cloud-bigquery`
https://github.com/conda-forge/google-cloud-bigquery-feedstock/pull/117
The build is failing and I traced it back to this migration not having happened.  It appears the bot couldn't solve the migration.  I'm opening this PR in the hopes that it either just works or help us figure out what needs to happen in order to make it work.

**Comment by xylar** [comment]
```
package grpc-cpp-1.47.0-h00ec82a_1 requires abseil-cpp >=20211102.0,<20211102.1.0a0, but none of the providers can be installed
```

**Comment by xylar** [comment]
Maybe needs https://github.com/conda-forge/grpc-cpp-feedstock/pull/195?

**Comment by coryan** [comment]
> Maybe needs [conda-forge/grpc-cpp-feedstock#195](https://github.com/conda-forge/grpc-cpp-feedstock/pull/195)?

I believe these are the problems we have to workaround:

- grpc <= 1.47.0 cannot use Abseil >= 20220623 
- That got fixed in https://github.com/grpc/grpc/pull/30145 which got released with grpc == 1.47.1
- grpc >= 1.48.0 cannot use Abseil < 20220623

I think that suggests the following order for the updates:

- Update gRPC to 1.47.1
- Update all downstream recipes to use gRPC >= 1.47.1
- Update Abseil to 20220623
- Update all downstream recipes to use Abseil >= 20220623
- Then update gRPC 1.48.0

**Comment by xylar** [comment]
@coryan, thanks for the information.  It sounds like you know much more about this than I do.  I'll be happy to close this but it sounds like an issue should be opened to keep track of these upgrades.  I'll try to keep an eye on it.

**Pull request closed without merging**
