### PR TITLE
The patch version affects the ABI

### PR DESCRIPTION
**Pull request by coryan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Hey @coryan 
Thanks a lot for this! Is it _just_ the inline namespace that changes (always or by default...), or does the ABI actually change? If so, we might just patch this out.

Not that I have something against pinning to patch level, but this then probably means that we won't necessarily be migrating for patch versions (assuming they're not quarters or more apart), because that creates just too much churn.

Assuming we need to go down to patch level, then for the 2.2.x series, we have builds with the "wrong" info out-and-about already, which means we have the choice to:
* not release other packages from the 2.2.x series
* add a repodata-patch for the _0 builds

(the builds would be correct as of this PR, but since they're more restrictive, the solver might often just end up choosing previous builds otherwise)

**Comment by coryan** [comment]
@conda-forge-admin, please rerender

> Hey @coryan Thanks a lot for this! Is it _just_ the inline namespace that changes (always or by default...),

The inline namespace *always* changes.

> or does the ABI actually change? If so, we might just patch this out.

The ABI includes the inline namespace.  For example, `google::cloud::storage::Client` (the code that people type) is really `google::cloud::storage::v2_2_0::Client` in the `.a` and `.so` files.


> Not that I have something against pinning to patch level, but this then probably means that we won't necessarily be migrating for patch versions (assuming they're not quarters or more apart), because that creates just too much churn.

That makes total sense.

> Assuming we need to go down to patch level, then for the 2.2.x series, we have builds with the "wrong" info out-and-about already, which means we have the choice to:
> 
> * not release other packages from the 2.2.x series
> * add a repodata-patch for the _0 builds

I think the first option is the right one.  The 2.3.x series is just 2 weeks away, and the 2.2.x series will get an uninteresting patch (as I mentioned elsewhere, it just affects the Bazel dependency file, which is unused by Conda).

> (the builds would be correct as of this PR, but since they're more restrictive, the solver might often just end up choosing previous builds otherwise)

Ack.

PS: I have not re-rendered in this PR, should I?

**Comment by h-vetinari** [comment]
> I think the first option is the right one. The 2.3.x series is just 2 weeks away, and the 2.2.x series will get an uninteresting patch (as I mentioned elsewhere, it just affects the Bazel dependency file, which is unused by Conda).

Well, with the bot auto merge being on, #117 still got merged, which means builds against the old 2.2.0 will now receive 2.2.1 at runtime and presumably break.

Could you submit a patch to conda-forge-repodata-patches to mark the 2.2.1 builds as broken?

**Comment by h-vetinari** [comment]
This is leading to breakage of existing arrow builds (see issue link above).

**Comment by h-vetinari** [comment]
I'll open a PR to mark 2.2.1 as broken as soon as I get to a computer in a couple hours, but anyone can do it and is welcome to (example [PR](https://github.com/conda-forge/admin-requests/pull/451) for reference).

**Comment by coryan** [comment]
I think I just sent such a PR.

**Pull request merged**
