### PR TITLE
feat: build all libraries in the package

### LINKED ISSUE #115: Add all features to the package
### Comment:

`google-cloud-cpp` supports many (currently optional) features.  The Conda package only builds the default features (`bigtable`, `bigquery`, `iam`, `logging`, `pubsub`, `spanner`, and `storage`), but there are dozens more:

https://github.com/googleapis/google-cloud-cpp/blob/main/ci/etc/full_feature_list

I think the correct way to implement this for conda is to create a subpackage for each feature.  That would greatly increase the number of subpackages, and may require some manual work to add new subpackages when features are created.

One benefit of creating these subpackages is more fine grained dependencies.  The storage library would drop its dependency on `grpc` and `libprotobuf`, and the other libraries would drop their dependency on `libcurl`, `crc32c`, and `nlohmann_json`.

In addition, the packages for Windows would get smaller, at least the ones only using one feature.

There are at least 3 common components that all features would need to depend on, `common`, `grpc_utils`, and `rest_internal`.  These are largely useless as standalone libraries, but it does not seem overly burdensome to create them.

The alternative is to keep the current structure, but enable *all* features in the build.  That will make the packages rather large and is probably not a good idea.

### PR DESCRIPTION
**Pull request by coryan**
By default `google-cloud-cpp` only builds the most commonly used libraries. When building from source that can save some time, but for package managers this leaves out many important features.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] Ensured the license file is being packaged.

Fixes #115 

I had to leave out a few libraries (`google/cloud/asset`, `google/cloud/channel`, and `google/cloud/storagetransfer`).  The proto files for these libraries use enum value names (e.g. `DOMAIN`) which are also defined as macros in the system libraries or in the C++ standard library. With all but the latest version of Protobuf this is not a problem.  With older versions it can be a problem with some compilers and C++ standard libraries (the list seems really hard to nail down).

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks for this @coryan! 

W.r.t to protobuf, looking at some of the issues (e.g. https://github.com/googleapis/google-cloud-cpp/issues/8145), it says that it needs protobuf >3.19.3; however we're at 3.21.12 already[^1] - does that change anything?

[^1]: We've had no problems with migrating to newer protobufs recently; I've been waiting for 3.22 for a while, but it seems it's getting a bit delayed (originally I heard it was supposed to arrive Nov' 22).

**Comment by coryan** [comment]
> Thanks for this @coryan!
> 
> W.r.t to protobuf, looking at some of the issues (e.g. [googleapis/google-cloud-cpp#8145](https://github.com/googleapis/google-cloud-cpp/issues/8145)), it says that it needs protobuf >3.19.3; however we're at 3.21.12 already[1](#user-content-fn-1-132c9b2b008d6ae201e8c26cc7928603) - does that change anything?

It is a sad, sad story.  We thought it only affected macOS, the [fixes](https://github.com/protocolbuffers/protobuf/commit/ab4585a6956675ce14a1cba5d321fde980bbf12b) are in.  But it also affects Windows, and I cannot find any fixes for that.  I will need to send new patches.

> 1. We've had no problems with migrating to newer protobufs recently; I've been waiting for 3.22 for a while, but it seems it's getting a bit delayed (originally I heard it was supposed to arrive Nov' 22). [↩](#user-content-fnref-1-132c9b2b008d6ae201e8c26cc7928603)

Things are moving.  There are two release candidates for v22.0. 
 The latest is [v22.0-rc2](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0-rc2).  However, it will not be 3.22, but **4.**22.  That is a new major release for C++ with some breaking changes.  And it is known to break gRPC.  I am not sure how the upgrades will need to proceed.

**Comment by h-vetinari** [comment]
> But it also affects Windows, and I cannot find any fixes for that. I will need to send new patches.

OK good to know thanks. If the patches aren't too big we can already carry them in conda-forge (within reason).

> That is a new major release for C++ with some breaking changes.

Breaking ABI and/or API? The former is a given (what we've been dealing with so far; just recompile), the latter would be harder to deal with, because it'll possibly need source adaptation).

**Comment by h-vetinari** [comment]
> The latest is [v22.0-rc2](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0-rc2). However, it will not be 3.22, but **4.**22.

The 4 might just be for the python release, at least that's how it's been since 3.21.0. The tag is the same for 3.22.0, 4.22.0 & 22.0:
```
commit fa7a079c1136b2850e0227675c0379e8fde5c560 (HEAD, tag: v4.22.0-rc2, tag: v3.22.0-rc2, tag: v22.0-rc2)
Author: Protobuf Team Bot <protobuf-team-bot@google.com>
Date:   Thu Feb 2 11:44:51 2023 -0800

    Updating version.json and repo version numbers to: 22.0-rc2
```

This broke our bot in creative ways when it was rolled out, but my [request](https://github.com/protocolbuffers/protobuf/issues/10497) to distinguish the tag patterns was rejected.

**Comment by coryan** [comment]
> > But it also affects Windows, and I cannot find any fixes for that. I will need to send new patches.
> 
> OK good to know thanks. If the patches aren't too big we can already carry them in conda-forge (within reason).

I will share a link to the patches as soon as they get exported.  I think they amount to 12 lines changed across 4 files.

> > That is a new major release for C++ with some breaking changes.
> 
> Breaking ABI and/or API? The former is a given (what we've been dealing with so far; just recompile), the latter would be harder to deal with, because it'll possibly need source adaptation).

Both.  You can see a partial list of changes in the [v22.0-rc1 Release Notes](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0-rc1).  Notable ones that I think affect Conda:

- The recipe will need changes to take a dependency on the [**latest** Abseil](https://github.com/abseil/abseil-cpp/releases/tag/20230125.0).
- Some header files used by `protoc` plugins changed.  That means `grpc` and anything downstream may need changes ([same errors without changes](https://github.com/googleapis/google-cloud-cpp/runs/11012639705)).
- If your proto uses words reserved by C++20, then the generated code is now different. Very few protos did this, none of the protos published by Google Cloud (where I work did).  But you never know. 

> The 4 might just be for the python release, at least that's how it's been since 3.21.0. 

See the release notes, they explicitly call out breaking changes to C++ and Ruby.

**Comment by h-vetinari** [comment]
> > The 4 might just be for the python release, at least that's how it's been since 3.21.0.
> 
> See the release notes, they explicitly call out breaking changes to C++ and Ruby.

Yeah, and I just found https://github.com/protocolbuffers/protobuf/blob/main/version.json, which notes the major versions.

**Pull request merged**
