### PR TITLE
fix: automatically install nlohmann_json

### LINKED ISSUE #28: nlohmann_json needed for using google-cloud-cpp via cmake in 1.17.0+
Issue: As of google-cloud-cpp 1.17.0+, using it via cmake does a search for `nlohmann_json` and errors if not found. Should this be specified as a runtime dependency or is it the user's responsibility to add the `nlohmann_json` package as well?

Relevant PR: https://github.com/googleapis/google-cloud-cpp/pull/4747

### PR DESCRIPTION
**Pull request by coryan**
Fixes #28. Implemented the fix suggested in said issue. Seems to work and other packages do similar things.

### CODE REVIEW

**Comment by coryan** [comment]
Rebased to resolve conflicts, PTAL.

**Comment by xhochy** [comment]
Sorry for not getting to this earlier. The right solution here would be to split the package into a contains-everything output and a runtime only output. Once the Windows PR is merged, I can push that approach here.

**Comment by coryan** [comment]
Should we close this PR then?  Happy either way.

**Comment by xhochy** [comment]
No, keep it open as I will push here. It also serves as a reminder for me.

**Pull request closed without merging**
